### ISSUE TITLE
Add API to directly start the core

### ISSUE THREAD

**Issue by Enjection** [tomsksoft-llc/cis1-proxy-go#4]

**Comment by ghostinecatnewyear** [comment]
Пока что реализовал только каркас маршрутизации для первоначального ревью: захардкодил передачу HTTP-ответов с отчётом о запуске задачи и с уведомлением о несуществующем ресурсе.

**Comment by ghostinecatnewyear** [comment]
Реализовал конфигурируемый запуск ядра.
